<a href="https://colab.research.google.com/github/7-Aishwarya/Data-Science-Python-Basics/blob/main/arithmeticoperationusingnumpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
a = np.array([[1,2,3],[4,5,6]])
a


array([[1, 2, 3],
       [4, 5, 6]])

In [3]:
b = np.array([7,8,9])
b

array([7, 8, 9])

In [4]:
np.add(a,b)

array([[ 8, 10, 12],
       [11, 13, 15]])

In [5]:
np.subtract(b,a)

array([[6, 6, 6],
       [3, 3, 3]])

In [6]:
np.multiply(a,b)

array([[ 7, 16, 27],
       [28, 40, 54]])

In [7]:
np.divide(a,b)

array([[0.14285714, 0.25      , 0.33333333],
       [0.57142857, 0.625     , 0.66666667]])

In [8]:
np.power(a,2)

array([[ 1,  4,  9],
       [16, 25, 36]])

In [9]:
np.power(b,3)

array([343, 512, 729])

In [11]:
np.power(a,b)

array([[       1,      256,    19683],
       [   16384,   390625, 10077696]])