<a href="https://colab.research.google.com/github/7-Aishwarya/Data-Science-Python-Basics/blob/main/Commonmathndstatsnumpy_py.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [2]:
np.min(arr)

1

In [3]:
np.max(arr)

9

In [5]:
np.amin(arr,axis=1)

array([1, 4, 7])

In [7]:
np.mean(arr)

5.0

In [11]:
np.median(arr)

5.0

In [12]:
np.std(arr)

2.581988897471611

In [14]:
np.var(arr)

6.666666666666667

In [15]:
np.percentile(arr,100)

9.0

In [16]:
deg = np.array([0,1,2,3,4])
np.sin(deg*np.pi/180)

array([0.        , 0.01745241, 0.0348995 , 0.05233596, 0.06975647])

In [17]:
np.cos(deg*np.pi/180)

array([1.        , 0.9998477 , 0.99939083, 0.99862953, 0.99756405])

In [20]:
np.tan(deg*np.pi/180)

array([0.        , 0.01745506, 0.03492077, 0.05240778, 0.06992681])

In [22]:
np.arctan(deg*np.pi/180)

array([0.        , 0.01745152, 0.03489242, 0.05231211, 0.06970008])

In [23]:
'''arcsin
arccos
arctan'''

'arcsin\narccos\narctan'

In [24]:
x = np.array([1.0,0.2,2.2,9.8,5.2])
np.floor(x)

array([1., 0., 2., 9., 5.])

In [25]:
np.ceil(x)

array([ 1.,  1.,  3., 10.,  6.])