<a href="https://colab.research.google.com/github/7-Aishwarya/Data-Science-Python-Basics/blob/main/Slicing_Indexing_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
one_array= np.array([1,2,3,4,5,6,7,8,9])
one_array


array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
two_array = np.array([[1,2,3],[4,5,6]])
two_array

array([[1, 2, 3],
       [4, 5, 6]])

In [9]:
three_array = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
three_array

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [10]:
one_array[0]
one_array[-1]

9

In [11]:
two_array[0:5]

array([[1, 2, 3],
       [4, 5, 6]])

In [12]:
one_array[0:8]

array([1, 2, 3, 4, 5, 6, 7, 8])

In [13]:
one_array[:9]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
two_array[1,2]

6

In [18]:
three_array[0,1,2]

6

In [19]:
three_array[1,1,-1]

12

In [21]:
two_array[1,1:]

array([5, 6])

In [22]:
two_array[0,0:]

array([1, 2, 3])

In [23]:
two_array[0,0:2]

array([1, 2])

In [24]:
two_array[0,0:3]

array([1, 2, 3])

In [25]:
three_array[0,1:,1:]

array([[5, 6]])

In [27]:
three_array[1,0:1:]

array([[7, 8, 9]])